export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESSED = 'CREATE_ISSUE_SUCCESSED';
export const CREATE_ISSUE_FAILED = 'CREATE_ISSUE_FAILED';

export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESSED = 'FETCH_ISSUES_SUCCESSED';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';

export const ISSUES_CLOSE_NOTIFICATION = 'ISSUES_CLOSE_NOTIFICATION';
