export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESSED = 'CREATE_ISSUE_SUCCESSED';
export const CREATE_ISSUE_FAILED = 'CREATE_ISSUE_FAILED';

export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESSED = 'DELETE_ISSUE_SUCCESSED';
export const DELETE_ISSUE_FAILED = 'DELETE_ISSUE_FAILED';

export const OPEN_ISSUE_EDITOR = 'OPEN_ISSUE_EDITOR';

export const GET_ISSUE_REQUEST = 'GET_ISSUE_REQUEST';
export const GET_ISSUE_SUCCESSED = 'GET_ISSUE_SUCCESSED';
export const GET_ISSUE_FAILED = 'GET_ISSUE_FAILED';

export const EDIT_ISSUE_REQUEST = 'EDIT_ISSUE_REQUEST';
export const EDIT_ISSUE_SUCCESSED = 'EDIT_ISSUE_SUCCESSED';
export const EDIT_ISSUE_FAILED = 'EDIT_ISSUE_FAILED';

export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESSED = 'FETCH_ISSUES_SUCCESSED';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';

export const DOWNLOAD_ATTACHMENT_REQUEST = 'DOWNLOAD_ATTACHMENT_REQUEST';
export const DOWNLOAD_ATTACHMENT_SUCCESSED = 'DOWNLOAD_ATTACHMENT_SUCCESSED';
export const DOWNLOAD_ATTACHMENT_FAILED = 'DOWNLOAD_ATTACHMENT_FAILED';

export const ISSUES_CLOSE_NOTIFICATION = 'ISSUES_CLOSE_NOTIFICATION';
