export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESSED = 'USER_CREATE_SUCCESSED';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSED = 'USER_LOGIN_SUCCESSED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESSED = 'USER_LOGOUT_SUCCESSED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESSED = 'USER_UPDATE_SUCCESSED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_CLOSE_NOTIFICATION = 'USER_CLOSE_NOTIFICATION';
